# Generated by Django 4.2.16 on 2025-01-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0005_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_order',
            name='desconto',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
